### ISSUE TITLE
Thumbnails for ROI selection process guide

### ISSUE THREAD

**Issue by brandon-gallas** [DIDSR/HTT.home#75]
@emma-gardecki-FDA 

I received feedback from Amy. 
-I reviewed the process guide; looks good so far. Might be helpful to have small thumbnail images to cue reviewers to the steps.

Not urgent.

Maybe for the pitfalls, we should add a link to the CME training slides on the CME mirror.

Let me know when your revisions are ready for review here by providing a link to the document to review. Please use track changes so I can quickly see them.

**Comment by emma-gardecki-FDA** [comment]
I added the CME slide link in dev `caMicro-ProcessGuide-ROIselection.md` Let me know if you'd like other changes

Is there a way to link to a commit in a branch? Or only a merge commit in main?

**Comment by brandon-gallas** [comment]
duh
