### ISSUE TITLE
Please list publications in reverse chronological order

### ISSUE THREAD

**Issue by brandon-gallas** [DIDSR/HTT.home#83]
@emma-gardecki-FDA 

Please list publications in reverse chronological order. Most recent first. Oldest last.

Thanks

**Comment by emma-gardecki-FDA** [comment]
Done, commit: https://github.com/DIDSR/HTT.home/commit/8a3e0397de76d60fac9dc2dc246b42f5bd77e474

**Comment by brandon-gallas** [comment]
Thanks!
